title: Brionna Franklin
description: AI Programmer
github:
  zip_url: https://github.com/brionnafranklin/brionnafranklin.github.io/blob/master/Resume.pdf
  tar_url: https://github.com/brionnafranklin
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
